---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: bestretail

run:
  path: bestretail/ci/tasks/integration.sh
  args: [
    --input-dir, bestretail
  ]
