---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: bestretail
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-final

run:
  path: bestretail/ci/tasks/prepare-final.sh
  args: [
    --input-dir, candidate-release,
    --output-dir, prepare-final,
    --version-file, version/number,
    --input-manifest, bestretail/manifest.yml,
    --artifactId, bestretail,
    --packaging, war
  ]
